### DISCUSSION TITLE
Does Komga create a docker volume even when instructed to use bind mounts?

### DISCUSSION THREAD

**Discussion by n00b12345** [gotson/komga#1755] [Q&A] [answered]
This is my docker compose:

```
---
services:
  komga:
    image: gotson/komga
    container_name: komga
    volumes:
      - type: bind
        source: /home/user/Docker/komga/config
        target: /config
      - type: bind
        source: /home/user/Docker/komga/data
        target: /data
      - type: bind
        source: /etc/timezone #alternatively you can use a TZ environment variable, like TZ=Europe/London
        target: /etc/timezone
        read_only: true
    ports:
      - 25600:25600
    user: "1000:1000"
    # remove the whole environment section if you don't need it
    restart: unless-stopped
```

The thing is, even when I am using bind mounts, I find that a docker volume is created. 
 
When I check `docker volume ls`, I get this output:

```
DRIVER    VOLUME NAME
local     868771bff356a2f1bagjszae30447c40a5a5b9a51cf2df2360d1376b
```

I can confirm that this is from komga because it is freshly created when the container is started. I just wanted to know if this was normal behaviour or if I was making a mistake.

Thanks for helping!

**Comment by n00b12345** [comment, marked as answer]
I got an answer on the Discord channel about this being a volume for temporary files. And therefore not consuming much space and inconsequential for backups.

**Reply by dr3st** [reply]
If you are interessted in getting rid of this volume:

```yaml
services:
  komga:
    ....
    tmpfs:
    - /tmp:rw,size=64m,mode=01777,exec
    volumes:
    - /srv/containers/komga/config:/config
    - /srv/containers/komga/data:/data
```
You can create a memory based volume (tmpfs), the only point here is, you must set the exec flag, otherwise you get an Java error
```
/tmp/sqlite-3.48.0.0-4cd66ec2-0c85-4c0c-89f0-d01886f877ef-libsqlitejdbc.so: failed to map segment from shared object
```
