### DISCUSSION TITLE
unable to add healthchecks feature for docker image container

### DISCUSSION THREAD

**Discussion by alx-xlx** [gotson/komga#1773] [Q&A]
I am trying to put healthchecks in the docker container as guided by the [docker docs](https://docs.docker.com/reference/compose-file/services/#healthcheck). However it fails as there is no "curl, wget" etc when I try to shell in the container using `docker exec -t komga /bin/bash`.

Does anyone know how healthchecks can be done for komga docker container ??

here is my compose file

```
---
version: '3.3'
services:
  komga:
    image: gotson/komga
    container_name: komga
    volumes:
      - type: bind
        source: /home/ubuntu/data/
        target: /config
      - type: bind
        source: /media/
        target: /data
      - type: bind
        source: /etc/timezone #alternatively you can use a TZ environment variable, like TZ=Europe/London
        target: /etc/timezone
        read_only: true
    ports:
      - 25600:25600
    user: "1000:1000"
    # remove the whole environment section if you don't need it
    environment:
      - <ENV_VAR>=<extra configuration>
    # restart: unless-stopped
    labels:
      - sablier.enable=true
      - sablier.group=komga
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:25600"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

```
