### ISSUE TITLE
error during container init: error mounting "/etc/timezone" to rootfs at "/etc/timezone"…

### ISSUE THREAD

**Issue by nodecentral** [gotson/komga#1040]
### Steps to reproduce

Not sure, what to add other than I believed I had followed the installation guide for Docker (https://komga.org/installation/docker.html#docker-compose), but it keeps failing with the same `etc/timezone` error message. While I understand what’s expected regarding binding data and config, the timezone one is confusing me..

My Docker compose and the resulting error message is below. 
````
version: '3.3'
services:
  komga:
    image: gotson/komga
    container_name: komga
    volumes:
      - type: bind
        source: /share/Container/komga/config
        target: /config
      - type: bind
        source: /share/Container/komga/data
        target: /data
      - type: bind
        source: /etc/timezone 
        target: /etc/timezone
        read_only: true
    ports: 
      - 8010:8080
    user: "1005:1000"
    restart: unless-stopped
 ````

### Expected behavior

I expected it to install seamlessly/

### Actual behavior

Installation failed..

### Logs

Background task error for application_custom Komga: ERROR: for komga Cannot start service komga: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/etc/timezone" to rootfs at "/etc/timezone": mount /etc/timezone:/etc/timezone (via /proc/self/fd/6), flags: 0x5001: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type ERROR: for komga Cannot start service komga: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/etc/timezone" to rootfs at "/etc/timezone": mount /etc/timezone:/etc/timezone (via /proc/self/fd/6), flags: 0x5001: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type Encountered errors while bringing up the project.

### Komga version

Latest 

### Operating system

QNAP Linux

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.
