### ISSUE TITLE
Komga docker-compose won't auto start or start on reboot

### ISSUE THREAD

**Issue by war3zlod3r** [gotson/komga#1105]
### Steps to reproduce

```
ion: '3.3'
services:
  komga:
    image: gotson/komga
    container_name: komga
    volumes:
      - type: bind
        source: /home/user/komga/config
        target: /config
      - type: bind
        source: /home/user/MergerFS/Comics
        target: /data_old
      - type: bind
        source: /home/user/MergerFS/Manga
        target: /Manga
      - type: volume
        source: Comics
        target: /data
      - type: bind
        source: /etc/timezone
        target: /etc/timezone
    ports:
      - '8099:8080'
    user: '1000:1000'
    environment:
      - TZ=America/Chicago
    restart: unless-stopped
volumes:
  Comics:
    driver_opts:
      type: nfs
      o: 'addr=nas.local,nolock,soft,rw'
      device: ':/volume1/Shared/Comics'
```

### Expected behavior

I've tried `restart: always` `restart: unless-stopped` and neither seem to work.

### Actual behavior

This is the only container out of my 5 containers that won't auto start.

### Komga version

0.165.0 (2023-03-17)

### Operating system

Ubuntu 22.10

### Other details

I've attempted this on both docker-compose on windows 10 and on Ubuntu 22.10 with the same results. Any help on why this one container won't autostart would be greatly appreciated.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Probably not Komga specific. Try stackoverflow or stackexchange for docker related questions.

**Comment by war3zlod3r** [comment]
If someone has a configuration that works I’d like to compare and test with it. I’ve never in any version of Komga been able to make this work but it works on every other container I run. Any troubleshooting advice would be greatly appreciated.On Apr 7, 2023, at 4:48 AM, Gauthier ***@***.***> wrote:﻿
Probably not Komga specific. Try stackoverflow or stackexchange for docker related questions.

**Comment by rage1337** [comment]
> 

`---
version: '3.8'
services:
  komga:
    image: gotson/komga
    container_name: komga
    volumes:
      - type: bind
        source: /svcs/komga/config
        target: /config
      - type: bind
        source: /vault/comics
        target: /data
      - type: bind
        source: /svcs/komga/import
        target: /import
      - type: bind
        source: /usr/share/zoneinfo/Europe/Berlin
        target: /etc/timezone
        read_only: true
    ports:
      - 10008:8080
    user: "1000:1000"
    restart: unless-stopped
`

This works for me

**Comment by rage1337** [comment]
```
---
version: "3.8"
services:
  komga:
    image: gotson/komga
    container_name: komga
    volumes:
      - type: bind
        source: /svcs/komga/config
        target: /config
      - type: bind
        source: /vault/comics
        target: /data
      - type: bind
        source: /svcs/komga/import
        target: /import
      - type: bind
        source: /usr/share/zoneinfo/Europe/Berlin
        target: /etc/timezone
        read_only: true
    ports:
      - 10008:8080
    user: 1000:1000
    restart: unless-stopped

```

This works fine for me.
