### ISSUE TITLE
Sqlite timeout settings does not appear to have effect sometimes

### ISSUE THREAD

**Issue by morsok** [gotson/komga#1261]
### Steps to reproduce

Here's my komga config:

```
komga:
  database:
    # sets the retry timeout when SQLITE_BUSY error happens
    busy-timeout: 60s
    
    # changes the journal mode
    # accepted values are: DELETE, TRUNCATE, PERSIST, MEMORY, WAL, OFF
    # most likely to be set to wal if needed, check https://sqlite.org/wal.html for more details
    journal-mode: wal
    
    # pool size will determine the number of connections in the pool
    # this takes precedence over max-pool-size if set
    # defaults to undefined
    pool-size: 2
    
    # pragmas accepts a list of key/value pairs where:
    # - key is the pragma name (see https://www.sqlite.org/pragma.html)
    # - value is the pragma value
    pragmas:
      # here are some example pragmas
      page_size: 4096
      synchronous: NORMAL
```

### Expected behavior

Timeouts appear after 1min

### Actual behavior

Timeouts still appear after only 30sec

### Logs

```
2023-10-20T09:35:49.209+02:00 ERROR 1 --- [io-25600-exec-4] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: org.jooq.exception.DataAccessException: SQL [select distinct COLLECTION.ID, COLLECTION.NAME, COLLECTION.ORDERED, COLLECTION.SERIES_COUNT, COLLECTION.CREATED_DATE, COLLECTION.LAST_MODIFIED_DATE from COLLECTION left outer join COLLECTION_SERIES on COLLECTION.ID = COLLECTION_SERIES.COLLECTION_ID left outer join SERIES on COLLECTION_SERIES.SERIES_ID = SERIES.ID where (SERIES.LIBRARY_ID in (?) and COLLECTION.ID in (select distinct COLLECTION.ID from COLLECTION left outer join COLLECTION_SERIES on COLLECTION.ID = COLLECTION_SERIES.COLLECTION_ID left outer join SERIES on COLLECTION_SERIES.SERIES_ID = SERIES.ID left outer join SERIES_METADATA on COLLECTION_SERIES.SERIES_ID = SERIES_METADATA.SERIES_ID where SERIES.LIBRARY_ID in (?))) order by ((COLLECTION.NAME) collate COLLATION_UNICODE_3) asc limit ? offset ?]; SqliteUdfPool - Connection is not available, request timed out after 30000ms.] with root cause
java.sql.SQLTransientConnectionException: SqliteUdfPool - Connection is not available, request timed out after 30000ms.
```

### Komga version

1.6.1

### Operating system

Synology DS920+

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.
