### ISSUE TITLE
Error: Could not find or load main class org.springframework.boot.loader.JarLauncher

### ISSUE THREAD

**Issue by Beheer007** [gotson/komga#1351]
### Steps to reproduce

Start Docker Container on Synology (from command line using docker-compose up -d)

### Expected behavior

Application starts and is functional

### Actual behavior

Docker does start but is non-functional

### Logs

Following two lines keep getting repeated:

_Error: Could not find or load main class org.springframework.boot.loader.JarLauncher
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.loader.JarLauncher_

### Komga version

Latest

### Operating system

Linux (Synology)

### Installation method

Docker

### Other details

Content of docker-compose file:

```
---
version: "3"
services:
  komga:
    container_name: komga
    environment:
      - TZ=Europe/Amsterdam
      - PGID=101
      - PUID=1024
    hostname: komga
    image: gotson/komga
    network_mode: 'bridge'
    ports:
      - 25600:25600
    restart: always
    volumes:
        - /volume1/docker/komga/config:/config:rw
        - /volume1/docker/komga/data:/data:rw
    working_dir: /
```

### Acknowledgements

- [X] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.
