### ISSUE TITLE
Invalid Token Response Synology SSO

### ISSUE THREAD

**Issue by Drakon74** [gotson/komga#1368]
### Steps to reproduce

1. configured Oauth as described in the documentation
2. on the login page selected "Login with [Service Name]"
3. Little window opens where apparently the SSO transaction happens
4. Login page reloads displaying the error "invalid_token_response"

### Expected behavior

Should login.

### Actual behavior

Displays just "invalid_token_response"

### Logs

I censored them a little, hope thats okay.

```
2023-12-22T22:37:11.106+01:00  INFO 1 --- [task-27] o.g.k.i.security.LoginListener           : AuthenticationActivity(userId=null, email=, ip=[Actual IP], userAgent=[Correct UserAgent], success=false, error=No AuthenticationProvider found for org.springframework.security.oauth2.client.authentication.OAuth2LoginAuthenticationToken, dateTime=2023-12-22T22:37:11.106468492, source=OAuth2:synology)
2023-12-22T22:37:11.153+01:00  WARN 1 --- [http-nio-25600-exec-11] o.s.web.servlet.PageNotFound             : No mapping for GET /login
2023-12-22T22:37:11.368+01:00  WARN 1 --- [http-nio-25600-exec-9] o.s.web.servlet.PageNotFound             : No mapping for GET /login
```

### Komga version

1.9.2

### Operating system

MacOS

### Installation method

Docker

### Other details

I am using this on a Synology NAS with Synologies SSO Server.

With that the URIs seem a bit different and are like this:

```
issuer-uri: https://[Domain]:5001/webman/sso

authorization-uri: https://[Domain]:5001/webman/sso/SSOOauth.cgi
token-uri: https://[Domain]:5001/webman/sso/SSOAccessToken.cgi
jwk-set-uri: https://[Domain]:5001/webman/sso/openid-jwks.json
user-info-uri: https://[Domain]:5001/webman/sso/SSOUserInfo.cgi
```

I tried with both just the issuer-uri and then with the 4 seperate ones, same result. I got the seperate URLs from the ".well-known" file.

The SSO Server itself reports in the log that the login of the User for the Komga Application was successfull. The same SSO Server works fine in a Gitea instance hosted on the same system.

Also note, in the reverse proxy confguration i set this header, so Komga uses the port, as without it, it would not attach the needed "5001" to the request to the SSO Server and the return URL.

`X-Forwarded-Host $host:5001`

### Acknowledgements

- [X] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by Drakon74** [comment]
Forgot the application.yml, sorry:

```
spring:
  security:
    oauth2:
      client:
        registration:
          synology:
            provider: synology # this must match the provider below
            client-id: [ID]
            client-secret: [Secret]
            client-name: synology
            scope: openid,email
            authorization-grant-type: authorization_code
            # the placeholders in {} will be replaced automatically, you don't need to change this line
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
        provider:
          synology: # this must match the provider above
            user-name-attribute: sub
            # either set the issuer-uri, in which case the app will lookup the configuration for you automatically
            #issuer-uri: https://[Domain]:5001/webman/sso
            authorization-uri: https://[Domain]:5001/webman/sso/SSOOauth.cgi
            token-uri: https://[Domain]:5001/webman/sso/SSOAccessToken.cgi
            jwk-set-uri: https://[Domain]:5001/webman/sso/openid-jwks.json
            user-info-uri: https://[Domain]:5001/webman/sso/SSOUserInfo.cgi
```
