### ISSUE TITLE
When OAuth2 login is enabled, SERVER_SERVLET_SESSION_TIMEOUT seems not to take effect properly

### ISSUE THREAD

**Issue by NagaseYami** [gotson/komga#1501]
### Steps to reproduce

- Run komga with Docker
- Run Authelia with Docker
- Follow [this guide](https://www.authelia.com/integration/openid-connect/komga/) to setup OAuth2
- Sign in with Authelia
- Restart my browser
- Now I have to sign in again

Here is my application.yml file, which is almost identical to the example from Authelia, except that I [added a session setting.](https://komga.org/docs/installation/configuration/#server_servlet_session_timeout--serverservletsessiontimeout-duration)
```yaml
komga:
  oauth2-account-creation: true
server:
  servlet:
    session:
      timeout: 7d
spring:
  security:
    oauth2:
      client:
        registration:
          authelia:
            client-id: komga
            client-secret: <my-secret>
            client-name: Authelia
            scope: openid,profile,email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseScheme}://{baseHost}{basePort}{basePath}/login/oauth2/code/authelia"
        provider:
          authelia:
            issuer-uri: https://auth.example.com
            user-name-attribute: preferred_username
```

### Expected behavior

`server.servlet.session.timeout` works.

### Actual behavior

Every time I restart the browser, I need to sign in again.

### Komga version

v1.11.1-master

### Operating system

Windows 11 & Chromium 124.0.6367.156-r1274542

### Installation method

Docker

### Acknowledgements

- [X] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.
