### ISSUE TITLE
Read progress is not tracked for each user separately

### ISSUE THREAD

**Issue by mistadikay** [gotson/komga#1620]
### Steps to reproduce

Hi. It seems that read progress is not tracked for each user separately. I'm running komga with docker-compose (see below). I have an admin account and I created another account. 

### Expected behavior

When I mark a book as "read" in any of the accounts, it should not change its read status in another account.

### Actual behavior

When I mark a book as "read" in any of the accounts, it is getting marked as "read" in another.

### Komga version

1.11.1

### Operating system

  Ubuntu 24.04 LTS

### Installation method

Docker

### Other details

```yaml
---
version: '3.3'
services:
  komga:
    image: gotson/komga
    container_name: komga
    volumes:
      - type: bind
        source: ./config
        target: /config
      - type: bind
        source: ./data
        target: /data
      - type: bind
        source: /etc/timezone #alternatively you can use a TZ environment variable, like TZ=Europe/London
        target: /etc/timezone
        read_only: true
    ports:
      - 25600:25600
    user: "1000:1000"
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx2g
    restart: unless-stopped
```

### Acknowledgements

- [X] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.
