### ISSUE TITLE
Docker and GLocker too often allocating

### ISSUE THREAD

**Issue by stanthewizzard** [gotson/komga#1628]
### Steps to reproduce

reading

### Expected behavior

be able to read

### Actual behavior

komga stops responding

### Logs

2024-07-24T18:26:34.174+02:00  INFO 1 --- [askProcessor-15] o.g.komga.application.tasks.TaskHandler  : Task FindDuplicatePagesToDelete(libraryId='0F037Q302N6H0', priority='0') executed in 1.257939ms
2024-07-24T18:35:05.111+02:00  INFO 1 --- [      task-1771] o.g.k.i.security.LoginListener           : AuthenticationActivity(userId=0CF0HDH5HPA22, email=xxxxxxxxxxxxx@icloud.com, ip=192.168.10.30, userAgent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Mobile/15E148 Safari/604.1, success=true, error=null, dateTime=2024-07-24T18:35:05.111609631, source=RememberMe)
2024-07-24T18:35:05.242+02:00  INFO 1 --- [      task-1771] o.g.k.i.security.LoginListener           : AuthenticationActivity(userId=0CF0HDH5HPA22, email=xxxxxxxxxxxxxx@icloud.com, ip=192.168.10.30, userAgent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Mobile/15E148 Safari/604.1, success=true, error=null, dateTime=2024-07-24T18:35:05.242751410, source=RememberMe)
2024-07-24T18:35:07.080+02:00  WARN 1 --- [o-25600-exec-18] o.s.web.servlet.PageNotFound             : No mapping for GET /book/0G52VAHWX9ZJV/read
2024-07-24T18:36:43.255+02:00  WARN 1 --- [o-25600-exec-16] o.s.web.servlet.PageNotFound             : No mapping for GET /book/0G52VAHWX9ZJV/read
[52314.781s][warning][gc,alloc] http-nio-25600-exec-65: Retried waiting for GCLocker too often allocating 1026 words
[52314.781s][warning][gc,alloc] http-nio-25600-exec-33: Retried waiting for GCLocker too often allocating 203 words
[52314.782s][warning][gc,alloc] http-nio-25600-exec-71: Retried waiting for GCLocker too often allocating 17480 words
[52314.782s][warning][gc,alloc] http-nio-25600-exec-76: Retried waiting for GCLocker too often allocating 16904 words
[52314.782s][warning][gc,alloc] http-nio-25600-exec-38: Retried waiting for GCLocker too often allocating 1026 words
[52314.782s][warning][gc,alloc] http-nio-25600-exec-57: Retried waiting for GCLocker too often allocating 1755 words
[52314.783s][warning][gc,alloc] http-nio-25600-exec-53: Retried waiting for GCLocker too often allocating 256 words
[52314.783s][warning][gc,alloc] http-nio-25600-exec-31: Retried waiting for GCLocker too often allocating 514 words
[52314.783s][warning][gc,alloc] http-nio-25600-exec-66: Retried waiting for GCLocker too often allocating 1742 words
[52314.783s][warning][gc,alloc] http-nio-25600-exec-88: Retried waiting for GCLocker too often allocating 256 words
[52314.783s][warning][gc,alloc] http-nio-25600-exec-34: Retried waiting for GCLocker too often allocating 17212 words
[52314.783s][warning][gc,alloc] http-nio-25600-exec-49: Retried waiting for GCLocker too often allocating 256 words
[52315.199s][warning][gc,alloc] http-nio-25600-exec-28: Retried waiting for GCLocker too often allocating 6625602 words
2024-07-24T18:57:01.432+02:00  WARN 1 --- [o-25600-exec-38] o.a.p.contentstream.PDFStreamEngine      : No more memory for cache: 98304
2024-07-24T18:57:01.443+02:00  WARN 1 --- [o-25600-exec-65] o.a.p.contentstream.PDFStreamEngine      : No more memory for cache: 172032
[52317.030s][warning][gc,alloc] http-nio-25600-exec-110: Retried waiting for GCLocker too often allocating 6625602 words
[52317.075s][warning][gc,alloc] http-nio-25600-exec-113: Retried waiting for GCLocker too often allocating 6625602 words
[52317.076s][warning][gc,alloc] http-nio-25600-exec-93: Retried waiting for GCLocker too often allocating 6625602 words
[52317.076s][warning][gc,alloc] http-nio-25600-exec-100: Retried waiting for GCLocker too often allocating 6625602 words
[52317.300s][warning][gc,alloc] http-nio-25600-exec-98: Retried waiting for GCLocker too often allocating 6625602 words
[52317.390s][warning][gc,alloc] http-nio-25600-exec-90: Retried waiting for GCLocker too often allocating 142712 words
[52317.632s][warning][gc,alloc] http-nio-25600-exec-109: Retried waiting for GCLocker too often allocating 6625602 words
[52317.632s][warning][gc,alloc] http-nio-25600-exec-118: Retried waiting for GCLocker too often allocating 6625602 words
[52317.995s][warning][gc,alloc] http-nio-25600-exec-106: Retried waiting for GCLocker too often allocating 6625602 words
[52319.863s][warning][gc,alloc] http-nio-25600-exec-54: Retried waiting for GCLocker too often allocating 203 words
[52319.923s][warning][gc,alloc] http-nio-25600-exec-95: Retried waiting for GCLocker too often allocating 514 words
[52319.926s][warning][gc,alloc] http-nio-25600-exec-107: Retried waiting for GCLocker too often allocating 256 words
[52319.926s][warning][gc,alloc] http-nio-25600-exec-32: Retried waiting for GCLocker too often allocating 203 words
[52319.926s][warning][gc,alloc] http-nio-25600-exec-94: Retried waiting for GCLocker too often allocating 203 words
[52319.926s][warning][gc,alloc] http-nio-25600-exec-118: Retried waiting for GCLocker too often allocating 330 words
[52320.270s][warning][gc,alloc] http-nio-25600-exec-92: Retried waiting for GCLocker too often allocating 6625602 words
[52320.540s][warning][gc,alloc] http-nio-25600-exec-74: Retried waiting for GCLocker too often allocating 4802 words

### Komga version

1.11.1

### Operating system

Docker

### Installation method

Docker

### Acknowledgements

- [X] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
How much ram do you have on your system ? Seems you are trying to open a big PDF, how big is that file ?

**Comment by stanthewizzard** [comment]
6giga
110 meg
Not that big ?

Thanks

**Comment by gotson** [comment]
could be a crappy PDF

**Comment by stanthewizzard** [comment]
It's almost on every file

**Comment by stanthewizzard** [comment]
Photon os 5.0
Esxi 8.xx (latest and patched)
4 cpu
12 g of ram

Nothing special or different from others containers.

Komga is the only one to crash like that. Autoheal restart it after 3min.

**Comment by stanthewizzard** [comment]
I'll try to arme komga through Ethernet and a pc.
The occurrence appears in safari with an iPad (WiFi ? iPad os ?)

**Comment by gotson** [comment]
> I'll try to arme komga through Ethernet and a pc. The occurrence appears in safari with an iPad (WiFi ? iPad os ?)

i don't understand what you are saying. Are you saying it works with some browsers, but doesn't with other browsers?

could you share 1 of the PDF that causes the issue, so i can test it locally and see if it's a file issue?

**Comment by gotson** [comment]
> Photon os 5.0 Esxi 8.xx (latest and patched) 4 cpu 12 g of ram
> 
> Nothing special or different from others containers.
> 
> Komga is the only one to crash like that. Autoheal restart it after 3min.

can you share the docker compose you are using, or the docker command line to create the container ?

**Comment by stanthewizzard** [comment]
> > Photon os 5.0 Esxi 8.xx (latest and patched) 4 cpu 12 g of ram
> > Nothing special or different from others containers.
> > Komga is the only one to crash like that. Autoheal restart it after 3min.
> 
> can you share the docker compose you are using, or the docker command line to create the container ?

```
version: "3.3"
services:
  komga:
    image: gotson/komga:latest
    container_name: komga
    healthcheck:
      test:
        - CMD
        - bash
        - -c
        - exec 5<>/dev/tcp/127.0.0.1/25600
      start_period: 80s
      interval: 5s
      timeout: 5s
      retries: 3
    labels:
      - autoheal=true
      - com.centurylinklabs.watchtower.lifecycle.post-update="docker exec -u
        root -t -i komga /bin/bash -c 'apt update && apt install curl -y'"
    volumes:
      - type: bind
        source: ./config
        target: /config
      - type: bind
        source: /mnt/NAS/Bibliotheque
        target: /data
    ports:
      - 25600:25600
    user: 1000:1000
    # remove the whole environment section if you don't need it
    environment:
      - TZ=Europe/Paris
      - JAVA_TOOL_OPTIONS=-Xmx4g
    restart: unless-stopped
networks: {}
```
