### ISSUE TITLE
Use SQLite PRAGMA Optimize Causes Database Issues

### ISSUE THREAD

**Issue by touxiaoling** [gotson/komga#1761]
### Steps to reproduce

```yaml
komga:
  database:
    # sets the retry timeout when SQLITE_BUSY error happens
    busy-timeout: 30s

    # changes the journal mode
    # accepted values are: DELETE, TRUNCATE, PERSIST, MEMORY, WAL, OFF
    # most likely to be set to wal if needed, check https://sqlite.org/wal.html for more details
    journal-mode: wal

    # pool size will determine the number of connections in the pool
    # this takes precedence over max-pool-size if set
    # defaults to undefined
    # pool-size: 1

    # max-pool-size will determine the maximum number of connections in the pool
    # when set, the number of connections is set to the number of available processors capped at max-pool-size
    # defaults to 1
    max-pool-size: 8

    # pragmas accepts a list of key/value pairs where:
    # - key is the pragma name (see https://www.sqlite.org/pragma.html)
    # - value is the pragma value
    pragmas:
      optimize: 0xfffe
      page_size: 4096 # Increase page size to improve I/O performance
      synchronous: NORMAL # Balance between performance and data safety
      cache_size: -2000 # Increase cache size to improve query speed (in pages)
      temp_store: MEMORY # Store temporary tables in memory to improve access speed
      trusted_schema: false # Disable trusted mode to improve performance
```

### Expected behavior

The SQLite database will be optimized, and everything else should work smoothly.

### Actual behavior

I’m unable to find my account in Komga.

### Komga version

1.14.1

### Operating system

Truenas

### Installation method

Docker

### Other details

Hello, after reading the SQLite documentation, I found that it’s recommended to run PRAGMA optimize periodically. However, when I set application.yaml as shown below, I can’t access my existing account after starting Komga.Could anyone help me understand why this might be happening and suggest what I should do?

### Acknowledgements

- [X] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.
