### ISSUE TITLE
Custom fonts not working

### ISSUE THREAD

**Issue by highfredo** [gotson/komga#1849]
### Steps to reproduce

Add fonts in /config/fonts/

```
config/
  fonts/
    Merriweather/
      Merriweather-BlackItalic.ttf
      ....
    Literata/
      ....
```

 

### Expected behavior

The book should be displayed with the selected font

### Actual behavior

The UI detects them but when you select it it switches to the browser's default font, not the selected one.
The selected font is not installed on my OS

![Image](https://github.com/user-attachments/assets/300ccede-901c-4655-9ace-b3273345e027)

### Komga version

1.19.0

### Operating system

Docker, Debian Host. Edge browser on Windows

### Installation method

Docker

### Acknowledgements

- [x] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [x] I have written a short but informative title.
- [x] I have checked the [FAQ](https://komga.org/docs/faq).
- [x] I have updated the app to the latest version.
- [x] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Can you provide startup logs? Can you also check the browser's network tools / console and check for any errors in there?

**Comment by gharden91** [comment]
I am running into this issue as well. I can provide additional logs if necessary.

**Comment by zhen-huan-hu** [comment]
Not sure if related. When I used OTF fonts, it worked on my desktop computer, but not on iOS (I can still select the font but it just switches back to the system default font). Converting the fonts WOFF2 solves the issue.

**Comment by gharden91** [comment]
OTF fonts **do not** work for me on Web/Windows and Edge/iOS.
woff2 Fonts **do** work for me on Web/Windows and Edge/iOS.

**Comment by gotson** [comment]
Can you try other browsers ?

**Comment by gotson** [comment]
Seems like it's a browser/platform issue. For better compatibility you should always use woff2/woff.

**Comment by gotson** [comment]
I think the `format` part of the font in the css may be incorrect for otf/ttf, which may explain why it doesn't work on some browsers/platform.

Will fix that.

**Comment by gotson** [comment]
I've also updated the mediaType returned in the HTTP response for the fonts to reflect the proper media type instead of `application/octet-stream`

**Comment by highfredo** [comment]
> Can you try other browsers on Windows ?

Tried with Firefox and Chrome, it doesn't work.

woff2 fonts works just as @gharden91 said

**Comment by gotson** [comment]
if you can try the latest `master` and provide feedback whether the 2 related commits work, that would be great

**Comment by highfredo** [comment]
> if you can try the latest `master` and provide feedback whether the 2 related commits work, that would be great

Its works!

![Image](https://github.com/user-attachments/assets/9ae1d6e7-d0ab-4675-8d96-972a4b0962fd)

Tested with wls + edge

**Comment by highfredo** [comment]
I just noticed something else, but it happens with all fonts types.

It doesn't detect the font family well.

```css
@font-face {
    font-family: 'Merriweather';
    src: url('Merriweather-BoldItalic.ttf') format('truetype');
    font-weight: bold;
    font-style: italic;
}

@font-face {
    font-family: 'Merriweather';
    src: url('Merriweather-Black.ttf') format('truetype'),url('Merriweather-Regular.ttf') format('truetype'),url('Merriweather-Light.ttf') format('truetype');
    font-weight: normal;
    font-style: normal;
}

@font-face {
    font-family: 'Merriweather';
    src: url('Merriweather-LightItalic.ttf') format('truetype'),url('Merriweather-Italic.ttf') format('truetype'),url('Merriweather-BlackItalic.ttf') format('truetype');
    font-weight: normal;
    font-style: italic;
}

@font-face {
    font-family: 'Merriweather';
    src: url('Merriweather-Bold.ttf') format('truetype');
    font-weight: bold;
    font-style: normal;
}
```

For example, "Merriweather-Black" is loaded by default when font-weight: normal and font-style: normal instead of "Merriweather-Regular"
