### ISSUE TITLE
Cantook + Komga with SSO prevents login

### ISSUE THREAD

**Issue by cyclingwithelephants** [gotson/komga#1943]
I'm not entirely sure if this is a problem with Komga, or Cantook. I have observed that Cantook is able to follow redirections from other public libraries, which is leading me to file this ticket here

### Steps to reproduce

- Install Komga using Oauth2 with Authelia
- force SSO login only
- Configure Cantook as a client to komga.
- enter the komga catalog, and attempt to log in with SSO by clicking the login with sso button.

Komga config:
```yaml
  application.yml: |
    spring:
      config:
        import: optional:file:/config/authelia-secret.yml
      security:
        oauth2:
          client:
            provider:
              authelia:
                issuer-uri: https://authelia.redacted.com
            registration:
              authelia:
                client-id: <redacted>
                scope: openid,profile,email
                redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
```

Authelia config
```yaml
        - client_id: <redacted>
          client_name: komga
          client_secret: <redacted>
          public: false                       # confidential client (server‑side)
          authorization_policy: two_factor
          redirect_uris:
            - "https://books.redacted.com/login/oauth2/code/authelia"
          scopes: [openid, profile, email]
          grant_types: [authorization_code]   # default; explicit for clarity
          userinfo_signed_response_alg: none  # Komga doesn’t require sig/enc
          token_endpoint_auth_method: client_secret_basic
          require_pkce: false                 # Komga doesn’t support PKCE yet
```

### Expected behavior

I would expect a popup to appear, or for the page to redirect (based on Komga web UI behaviour, I would expect a popup) to enable me to authN with Authelia.

### Actual behavior

No popup appears, and I am therefore unable to login. 

### Logs

N/A

### Komga version

1.21.2

### Operating system

Linux server, ios client

### Installation method

Docker

### Other details

Kubernetes on linux

### Acknowledgements

- [x] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [x] I have written a short but informative title.
- [x] I have checked the [FAQ](https://komga.org/docs/faq).
- [x] I have updated the app to the latest version.
- [x] I will fill out all of the requested information in this form.
