### ISSUE TITLE
Komga does not load at all (502 or simply connection reset) - podman rootless

### ISSUE THREAD

**Issue by jessienab** [gotson/komga#1985]
### Steps to reproduce

1. Run the image, `podman-compose up -d`
2. Wait for Tomcat to start up, starts fine
3. Forward port over ssh, `ssh -NTL 25600:localhost:25600 myserver &`
4. Try to load web interface... Firefox reports "The connection was reset", nothing in logs.

### Expected behavior

The web interface should load, as it's a direct port connection with only ssh assisting in networking; no reverse proxy. TRACE nor DEBUG show genuinely NO activity in logs.

### Actual behavior

The web interface doesn't load at all, and testing with nginx gives 502 gateway errors for upstream.

### Logs

Main log: [log.log](https://github.com/user-attachments/files/20579440/log.log)

### Komga version

1.21.3

### Operating system

Linux, Arch Linux

### Installation method

Docker

### Other details

I understand this is designed for Docker, but I had no issues running this previously with podman/podman-compose. Additionally, I am running podman rootless... but I have no issues with any other kind of package. Is Komga using some kind of permission that needs root (I don't think so since it'd be in config, or komga would crash right?).

docker-compose.yml:
```
---
version: '3.3'
services:
  komga:
    image: gotson/komga:1.21.3
    container_name: komga
    volumes:
      - /opt/pods/komga/config:/config
      - /mnt/Books:/data
    ports:
      - 127.0.0.1:25600:8080
    user: "1001:1001"
    environment:
      - LOGGING_LEVEL_ORG_GOTSON_KOMGA=DEBUG
      - PUID=1001
      - PGID=1001
      - TZ=America/Toronto
      - JAVA_TOOL_OPTIONS=-Xmx4g
    restart: unless-stopped
```

Thank you!

### Acknowledgements

- [x] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [x] I have written a short but informative title.
- [x] I have checked the [FAQ](https://komga.org/docs/faq).
- [x] I have updated the app to the latest version.
- [x] I will fill out all of the requested information in this form.
