### ISSUE TITLE
Latest version of Komga docker container does not work on Raspberry pi 4 (Armv7)

### ISSUE THREAD

**Issue by mahenkpatel** [gotson/komga#345]
### Komga environment
- **OS**: Raspberry Pi OS
- **Komga version**: v0.63.3-master
- [ ] **I am running Komga with Docker**
  - Docker image tag [e.g. latest, beta]: latest

### Describe the bug
Komga docker container has been running fine from last few months on my raspberry pi. I recently upgraded the komga container to latest and since then the server is no functional.

The container shows running but the server cannot be accessed.

I see below 1 line log after the container starts

```
pi@Raspi4:~/.docker $ docker logs -f komga
OpenJDK Server VM warning: No monotonic clock was available - timed services may be adversely affected if the time-of-day clock changes
```

I also tried to remove the container data along with container and reinstall it but the issue remains same. I also noticed that it does not create any file inside the /config directory when do a fresh install. The directory remains empty.

I installed the same version on an x64 Ubuntu server and it works fine without any issues. The problem seems to be with Arm image.

I am using below docker compose to install it. Note that the same was working fine up until the latest update.

```
  komga:
    image: gotson/komga:latest
    container_name: komga
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - $HOME/.docker/komga/config:/config
      - /hdd/Comics:/books
    ports:
      - 8055:8080
    restart: unless-stopped
```
