### ISSUE TITLE
[Bug] Komga not visible over wifi, if ethernet also connected when starting komga.

### ISSUE THREAD

**Issue by thFrgttn** [gotson/komga#681]
### Komga environment
- **OS**: Windows 10
- **Komga version** :0.126.0
- **I am running Komga from the `jar`**
  - Java version: 1.8.0_301

If I start Komga whilst I have a network connected via an ethernet cable prevents Komga being visible over my wifi (the computer on the other end of the cable can see Komga).
If I disconnect the cable before staring Komga its then visible on my wifi, and when the network is reconnected it becomes visible there also. (I only need it visible on the wifi).

Spring seems to have configuration options about ignoring interfaces and preferred networks, but either Komga dosen't support them or I'm not configuring them correctly. 
I tried adding the following to application.yml but it didn't seem to work.

```yml
spring:
  cloud:
    inetutils:
      ignoredInterfaces:
        - eth0
      preferredNetworks:
        - 10.0       
```
