### ISSUE TITLE
[Bug] Sessions expiring 

### ISSUE THREAD

**Issue by valdearg** [gotson/komga#717]
### Komga environment
- **OS**: Ubuntu 20.04
- **Komga version**: v0.132.0-master
- [ ] **I am running Komga with Docker**
  - Docker image tag [e.g. latest, beta]:
- [*] **I am running Komga from the `jar`**
  - Java version: openjdk 11.0.11 2021-04-20
- [*] **I have a problem in the web interface**
  - Browser (with version):
- [ ] **I have a problem with an OPDS client application**
  - OPDS Application (with version):
- [ ] **I have a problem with the Tachiyomi extension**
  - Tachiyomi version:
  - Tachiyomi extension version:

### Describe the bug
Since upgrading to the latest version after an unknown period of time (other than that it's a good deal of idle time) the session will expire.

Frequently I will get the error message:

`This session has been expired (possibly due to multiple concurrent logins being attempted as the same user).`

If I then refresh the tab I'm redirected to the login page.

As per the documentation on the 0.132.0 [here ](https://komga.org/installation/configuration.html#komga-sessiontimeout-komga-session-timeout-duration) I noticed the komga.session-timeout, I've set my application.yml as the following:

```
komga:
  libraries-scan-cron: "0 */15 * * * ?" #periodic scan every 15 minutes
  libraries-scan-directory-exclusions: #patterns to exclude directories from the scan
    - "#recycle" #synology NAS recycle bin
    - "@eaDir"   #synology NAS index/metadata folders
  filesystem-scanner-force-directory-modified-time: false #set to true only if newly added books in existing series are not scanned (ie Google Drive)
  remember-me.key: "random generated string"
  session-timeout: 14d
spring:
  datasource:
    url: jdbc:h2:./komga-database.h2 #database will be located in the current directory
  profiles:
    active: prod
```

This does give me a SESSION cookie along with a remember-me cookie in the browser.

If I close the browser for a long period of time (a couple of hours perhaps), I find myself logged out when I return. 

I've tried in Chrome and Firefox and get the same results, this also seems to effect my Tachiyomi as I sometimes hit issues with loading an image or fully get the session error message printed out.

### Steps to reproduce
1. Login to Komga in your browser
2. Leave it for a couple of hours and use the browser as normal.
3. Come back to the Komga tab, refresh the tab.
4. Should see either the error above or be redirected to the login page completely.

### Expected behaviour
The session should expire on the default 7 days or the 14 days specified. 

### Actual behaviour
Logged out and need to login.

### Additional context
I switched back to v0.130.0 to see if it was an issue with something else, but it seems to work without a problem on the older version.

### Log file
I couldn't see anything in the logs relevant, but can be provided as required.
