### ISSUE TITLE
Docker image fails to run properly due to permission issues, using podman

### ISSUE THREAD

**Issue by jasonnab** [gotson/komga#872]
### Steps to reproduce

1. Pull the docker-compose.yml file
2. Modify as needed
3. Launch using podman-compose up -d in the same folder as the .yml file
4. Komga will fail due to permission issues and cycle through restarts.

### Expected behavior

Komga should start up properly and be accessible over the system.

### Actual behavior

Komga will continuously cycle through it's startup process due to it failing to write a .lock file, and failure to write and read an sqlite database.

### Logs

> 2022-04-27 19:13:15.224  WARN 1 --- [           main] org.apache.activemq.artemis.core.server  : AMQ222141: Node Manager can not open file /config/artemis/journal/server.lock
> 
> java.io.IOException: No such file or directory

and

> java.sql.SQLException: opening db: '/config/database.sqlite': Permission denied

Full log attached.
[komga-error.log](https://github.com/gotson/komga/files/8575050/komga-error.log)

### Komga version

0.154.1

### Operating system

Arch Linux 5.16.14-arch1-1

### Other details

I am using podman in rootless mode, and I understand that presumably podman is _not_ supported compared to Docker.

However, my understanding is that podman is effectively compliant or compatible with most/all docker containers, excluding situations like this with permission issues.

The error here seems to be failure to write files to a specific folder, as it's owned by root, thus perhaps the expectation that the container would be run "as root" (which docker does normally). My personal suggestion in this case would be to modify the /config folder permission to a general user, or somehow map it to the running user's ID.

Here are my relevant config files and user IDs. I appreciate any help if it's possible, otherwise I can attempt running this by building a custom image, or as a bare metal system app.

Thanks!

---

docker-compose.yml: modified to read cleaner, change system-side port, and user to the container user. Timezone is set from environment variable.

```
---
version: '3.3'
services:
  komga:
    image: gotson/komga
    container_name: komga
    volumes:
      - /etc/container-config/komga/config:/config
      - /mnt/data/comics/:/data
    ports:
      - 12345:8080
    user: "1001:1001"
    environment:
      - LOGGING_LEVEL_ORG_GOTSON_KOMGA=DEBUG
      - TZ=Europe/Berlin
    restart: unless-stopped

```
$ podman exec -it komga /bin/bash
`1001@c42372a5033e:~$`

showing that the user is set to the correct ID

$ id
`uid=1001(containeru) gid=1001(containeru) groups=1001(containeru)`

showing the user id matches the user running containers

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.
