### ISSUE TITLE
App keeps restarting

### ISSUE THREAD

**Issue by notarobot63** [gotson/komga#886]
### Steps to reproduce

Launch container with docker-compose up -d

### Expected behavior

The expected behavior is that the app keeps running

### Actual behavior

Every few seconds the app is restarting after working normally for a while, with or without a configured library folder it's the same.

### Logs

This is the loop of logs I am having:
https://zerobin.net/?38714a949057309e#/uyGzk9nCbid1l6sQcQEwSgN8XTPiUQuknr3SzM3tfw=

### Komga version

0.154.1

### Operating system

Debian 11

### Other details

My Docker-compose:

```
version: '3.3'
services:
  komga:
    image: gotson/komga
    container_name: komga
    volumes:
      - type: bind
        source: ./config
        target: /config
      - type: bind
        source: /home/OMVBooks
        target: /books
      - type: bind
        source: /etc/timezone
        target: /etc/timezone
        read_only: true
    ports:
      - 8080:8080
    user: "1000:1000"
    # remove the whole environment section if you don't need it
    environment:
      - TZ=Europe/Paris
      - KOMGA_REMEMBERME_KEY=gfdsg5f4ds4g6fd4sg4fds
      - LOGGING_LEVEL_ORG_GOTSON_KOMGA=DEBUG
    restart: unless-stopped
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.
