### ISSUE TITLE
[Bug] cant login with admin generated using docker

### ISSUE THREAD

**Issue by albjeremias** [gotson/komga#94]
### Komga environment
- **OS**: 
- **Komga version**: 
- [x] **I am running Komga with Docker**
  - gotson/komga:0.14.1
- [ ] **I am running Komga from the `jar`**
  - Java version: 
- [ ] **I have a problem in the web interface**
  - Browser (with version): 
- [ ] **I have a problem with an OPDS client application**
  - OPDS Application (with version): 
- [ ] **I have a problem with the Tachiyomi extension**
  - Tachiyomi version: 
  - Tachiyomi extension version: 

### Describe the bug
When the docker image starts up... using docker-compose i get the output on the log of:
```
komga    | 2020-02-16 18:23:50.683  INFO 1 --- [           main] o.g.k.i.scheduler.InitialUserController  : No users exist in database, creating initial users
komga    | 2020-02-16 18:23:50.950  INFO 1 --- [           main] o.g.k.i.s.KomgaUserDetailsLifecycle      : Created user: admin@example.org, roles: [ADMIN]
komga    | 2020-02-16 18:23:51.051  INFO 1 --- [           main] o.g.k.i.scheduler.InitialUserController  : Initial user created. Login: admin@example.org, Password: xxxxx
```

### Steps to reproduce
1. Go to https://komga.server.com enter the login that appears in the log
2. get an error saying: " Invalid authentication "

### Expected behavior
I expected that I would be able to login, using the user created and provided on the logfile.

### Actual behavior
I can't login

### Additional context
my docker-compose file:
```
---
version: '3.3'
services:
  komga:
    image: gotson/komga:0.14.1
    container_name: komga
    volumes:
      - type: bind
        source: /live/storage/komga/config
        target: /config
      - type: bind
        source: /live/storage/komga/books
        target: /books
      - type: bind
        source: /etc/timezone
        target: /etc/timezone
        read_only: true
    labels:
     - "traefik.port=8080"
     - "traefik.frontend.rule=Host:library.domain.co"
    environment:
      - KOMGA_LIBRARIES_SCAN_DIRECTORY_EXCLUSIONS=#recycle,@eaDir
    restart: unless-stopped
    networks:
      - world

networks:
  world:
     external: true
```
