### ISSUE TITLE
Out of Memory Errors even after giving Java 8Gb

### ISSUE THREAD

**Issue by vorpalhex** [gotson/komga#946]
### Steps to reproduce

1. Bring up Komga
2. Komga crashes

### Expected behavior

1. Komga should run

### Actual behavior

1. Komga crashes with an OOM. 

### Logs

Pastebin of logs: https://pastebin.com/5VAcbRzV

docker-compose entry:
```
  komga:
    container_name: komga
    image: gotson/komga:latest
    user: "997:997"
    environment:
      - PUID=997
      - PGID=997
      - TZ=America/Chicago
      - JAVA_TOOL_OPTIONS=-Xmx8g
    restart: unless-stopped
    volumes:
      - /mnt/Apps/komga_config:/config
      - /mnt/Manga:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.komga.loadbalancer.server.port=8080"
      - "traefik.http.routers.komga.entrypoints=web"
```

output of `free -h` on host:
```
              total        used        free      shared  buff/cache   available
Mem:           62Gi        39Gi        10Gi        42Mi        12Gi        22Gi
Swap:            0B          0B          0B
```

### Komga version

latest

### Operating system

ubuntu server

### Other details

Even attempting to point Komga to an empty directory results in the exact same behavior.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.
