### ISSUE TITLE
crash with docker-compose because of database.sqlite  incorrect path 

### ISSUE THREAD

**Issue by mybuntu-git2** [gotson/komga#958]
### Steps to reproduce

I run the latest image with this docker-compose.yml
```yml
---
version: '3.3'
services:
  komga:
    deploy:
      resources:
       limits:
        cpus: '2.5'
        memory: 900M
    image: gotson/komga
    container_name: komga
    volumes:
      - type: bind
        source: /home/ubuntu/komga/conf
        target: /config
      - type: bind
        source: /home/ubuntu/sshfs_mounts/sshfs_permanent_mount_komga_data
        target: /data
      - type: bind
        source: /etc/timezone
        target: /etc/timezone
        read_only: true
    network_mode: "host"
    user: "1000:1000"
    # remove the whole environment section if you don't need it
    environment:
      - SERVER_PORT=51223
      - KOMGA_CONFIGDIR=/home/ubuntu/komga/conf
      - KOMGA_DATABASE_FILE=/home/ubuntu/komga/conf/database.sqlite
      - KOMGA_SESSIONTIMEOUT=6h
      - KOMGA_LIBRARIES_SCAN_STARTUP=true
      - KOMGA_DELETE_EMPTY_COLLECTIONS=false
    restart: unless-stopped
```
at first I had a crash on missing database.sqlite inside conf, so I added the line found above
` - KOMGA_DATABASE_FILE=/home/ubuntu/komga/conf/database.sqlite`

but now komga crashes on startup, stating:
`Caused by: java.sql.SQLException: path to '/home/ubuntu/komga/conf/database.sqlite': '/home/ubuntu' does not exist`

### Expected behavior

komga should create the database.sqlite if missing when config is empty
...but I guess I wrote the wrong path to the sqlite in any case.

### Actual behavior

komga crashes

### Komga version

0.157.1

### Operating system

ubuntu 20.04

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
please provide complete log file

**Comment by mybuntu-git2** [comment]
[komgalog.log](https://github.com/gotson/komga/files/9430233/komgalog.log)

**Comment by gotson** [comment]
You might need to check a Docker 101 tutorial on volumes and bind mounts.

Here you set paths that are _OUTSIDE_ the container:
```
 - KOMGA_CONFIGDIR=/home/ubuntu/komga/conf
 - KOMGA_DATABASE_FILE=/home/ubuntu/komga/conf/database.sqlite
```

While you mounted the folders like so:

```
    volumes:
      - type: bind
        source: /home/ubuntu/komga/conf
        target: /config
```

What the container sees is `/config`.

You should remove all of that, it's not necessary and automatically handled in the Docker version of Komga:
```
      - KOMGA_CONFIGDIR=/home/ubuntu/komga/conf
      - KOMGA_DATABASE_FILE=/home/ubuntu/komga/conf/database.sqlite
```
